### ISSUE TITLE
Fix address generation

### ISSUE THREAD

**Issue by HarryR** [hclivess/Bismuth_pool#1]
It is not calculated in the same way as Bismuth

**Comment by hclivess** [comment]
Fixed in https://github.com/hclivess/Bismuth_pool/commit/ed6de6bbc01f7af49b1418cb5b07d9d7b4cbe11d if that was the only place. Also dual address handling was added to Bismuth core code. Pool payout has been made.

**Comment by HarryR** [comment]
Awesome, that is an elegant fix
