### ISSUE TITLE
when  I  use  miner  to  dig   Bismuth  i  can't  find my Miner  in  https://bismuth.acc-pool.pw/

### ISSUE THREAD

**Issue by flyfire100** [hclivess/Bismuth_pool#5]
i  create  my  wallet in https://biswallet.acc-pool.pw/index.php
![image](https://user-images.githubusercontent.com/28288582/33241281-2db80bd6-d2fe-11e7-8579-569981b379c0.png)
then  i  follow the manual  https://bismuth.acc-pool.pw/ create my  miner
![image](https://user-images.githubusercontent.com/28288582/33241293-57806f62-d2fe-11e7-8a4d-d1625860f13d.png)
when my miner working，it look like this
![image](https://user-images.githubusercontent.com/28288582/33241308-7cc4615c-d2fe-11e7-8651-8464f6aa5fc7.png)
but  i can't  find my miner in https://bismuth.acc-pool.pw/
![image](https://user-images.githubusercontent.com/28288582/33241317-a07c83a4-d2fe-11e7-88da-e247d44968fc.png)

i don't know what's wrong，please  help me

**Comment by hclivess** [comment]
Hello, you need to go to to the acc pool slack, this is the Bismuth core repository
